project:
  name: TechnicalChallenge
  environment: dev
  region: ap-southeast-1

network:
  vpc_cidr: "10.0.0.0/16"
  private_subnets:
    - cidr: "10.0.1.0/24"
      az: "us-east-1a"
    - cidr: "10.0.2.0/24"
      az: "us-east-1b"

compute:
  instance_type: t3.micro 

state:
  bucket: s3-apse1-shared-terraform-state

iam:
  role_arn: "arn:aws:iam::261093894796:role/iam-apse1-dev-terraform-build" 

tags:
  ManagedBy: Terraform
  Owner: DevOps
  Project: Caladan
  Environment: dev
  CostCenter: Development
